name: Deploy to Production
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: "98.90.67.40"
          SERVER_USER: "ubuntu"

        run: |
          echo "Conectando ao servidor..."
          # Configura a chave SSH  no ambiente do Actions
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Desativa a verificação estrita de host para a primeira conexão
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

          echo "Iniciando o deploy no servidor..."

          # Comandos a serem executados DENTRO do servidor EC2
          ssh $SERVER_USER@$SERVER_IP << 'EOF'
            # Navega para a pasta do projeto
            cd /var/www/hub-do-cafe

            # Puxa as atualizações do Git
            git reset --hard
            git pull origin main

            # Instala dependências do Composer
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

            # Instala dependências do Node (Frontend)
            npm ci

            # Compila os assets (CSS/JS) para produção
            npm run build

            # Roda as migrações do banco de dados (se houver)
            php artisan migrate --force

            # Limpa e otimiza o cache do Laravel
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "Deploy finalizado com sucesso!"
          EOF
